import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideBar from "../_components/SideBar";
import { Navigation } from "../_components/Navigation";
import { NavigationProfile } from "../_components/NavigationProfile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// async function getUserData(userId: string) {
//   const res = await fetch(
//     `${process.env.NEXT_PUBLIC_API_URL}/users/auth/dashboard/${userId}`
//   );
//   if (!res.ok) {
//     return null;
//   }
//   return res.json();
// }
export async function generateMetadata({
  params,
}: {
  params: Promise<{ userId: string }>;
}): Promise<Metadata> {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/users/auth/dashboard/${
      (
        await params
      )?.userId
    }`
  );
  const user = await res.json();
  if (user) {
    return {
      title: `Profile of ${user.data.user.profile.name}`,
      description: `View the profile of ${user.data.user.profile.name}`,
      icons: {
        icon: user.data.user.profile.avatarImage || "/favicon.ico",
      },
    };
  }

  return {
    title: "User not found",
    description: "User not found!",
  };
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen overflow-x-hidden bg-background">
      {children}
    </div>
  );
}
